단어 추가 화면 피그마 디자인 반영
mwy3055/MyVoca pull request #148
Opened 2023-11-18 07:37 UTC by easyhooon

- 단어 추가 화면 피그마 디자인 반영 
- 추가할 단어의 의미 중복 검사 기능 추가

2023-11-18 07:39 UTC, easyhooon commented
웹뷰가 화면에 띄워질때 애니메이션이 필요하다고 생각되시면 말씀 해주시는 애니메이션으로 반영하겠습니다

2023-11-18 14:24 UTC, mwy3055 requested changes
지금까지는 제가 너무 바빠서 버그만 없으면 approve를 드렸는데, 이제는 여유가 조금 생겨서 자세히 볼 수 있을 것 같습니다. 

대충 이 PR에서 수정하신 파일의 디자인, 코드 리뷰를 한꺼번에 드립니다. 

1. 검색 버튼과 쓰레기통 버튼이 텍스트 뷰보다 살짝 아래로 치우쳐 있습니다. 가운데를 딱 맞출 수 있을까요?
![image](https://github.com/mwy3055/MyVoca/assets/45386920/0ef7a9fa-6e92-4353-bda3-28c76aa8ed83)
![image](https://github.com/mwy3055/MyVoca/assets/45386920/242893b2-1261-41e8-8de0-51a95f921211)

2. 뜻 추가 버튼은 항상 버튼 전체로만 클릭되어야 합니다. 개별 요소가 클릭되지 않게 수정해 주세요.
![image](https://github.com/mwy3055/MyVoca/assets/45386920/fe88711c-8443-47cc-90a2-b22429709f88)

3. 뜻 추가 버튼을 클릭할 때의 이펙트가 버튼에 딱 맞게 보일 수 있을까요? 즉, 클릭 이펙트가 둥근 사각형 모양으로 보이게 할 수 있을까요? 지금은 외곽에 뭐가 있는 것처럼 보입니다.
![image](https://github.com/mwy3055/MyVoca/assets/45386920/414ea87d-e570-4133-8f00-a8c1d8c1890a)

4. 뜻을 입력하는 textview의 라벨 텍스트 형식이 잘못되었습니다. `2 명사`가 아니라 `2. 명사`입니다.
![image](https://github.com/mwy3055/MyVoca/assets/45386920/2554db0f-dee1-4afc-ba46-3f9494d2c525)

5. 웹뷰 주변에 있는 padding을 없애 주세요. 
![image](https://github.com/mwy3055/MyVoca/assets/45386920/318ae801-13c1-4305-ba06-8561791c59ad)

6. 디자인 얘기는 아니지만, composable 코드에서 `modifier`가 최상위 container가 아닌 하위 composable에 적용된 코드가 많이 보입니다. 굳이 이렇게 하신 이유가 있나요? (예를 들어 `AddWordScreen.kt`의 `Meanings()`)
```Kotlin
@Composable
private fun Meanings(
    modifier: Modifier = Modifier,
    ...
) {
    // modifier가 이 Column에 적용되어야 할 것 같은데
    Column {
        // ...
        if (meanings.isEmpty()) {
            // 하위 composable에 적용됨
            MeaningsEmptyIndicator(
                modifier = modifier
                    .height(meaningHeight)
                    .fillMaxWidth()
            )
        } else {
             // ...
        }
    }
}
```

7. 일반적으로 Kotlin 함수의 매개변수는 default value가 없는 것들이 먼저 오고, 그 뒤에 default value가 있는 매개변수가 와야 합니다(Trailing lambda는 예외). Composable도 마찬가지로 default value가 없는 것, Modifier, default value가 있는 것 순서대로 와야 합니다. 이 PR을 포함하여 디자인 적용 PR에서 위 원칙대로 매개변수 순서를 바꿔 주시면 감사하겠습니다.

2023-11-18 16:44 UTC, easyhooon commented
> 1. 검색 버튼과 쓰레기통 버튼이 텍스트 뷰보다 살짝 아래로 치우쳐 있습니다. 가운데를 딱 맞출 수 있을까요?

아래 에러메세지가 쓰여질 부분의 공간까지 포함해서 중앙에 배치했긴했던건데(미리 공간을 할당 해놓지 않으면 에러메세지가 뜰 경우, 나머지 뜻 들이 아래로 밀리는 이슈가 있어서) 가운데로 맞출게여

2023-11-18 16:46 UTC, easyhooon commented
> 2번 3번

디테일한 지적 감사함니다

2023-11-18 16:48 UTC, easyhooon commented
> 디자인 얘기는 아니지만, composable 코드에서 modifier가 최상위 container가 아닌 하위 composable에 적용된 코드가 많이 보입니다. 굳이 이렇게 하신 이유가 있나요? (예를 들어 AddWordScreen.kt의 Meanings())

최상위 컨테이너에 modifier 가 사용되지 않아서 가장 처음으로 사용되는 modifier 에 적용한것으로 생각되긴하는데 최상위에 할당하는게 맞긴 하겠네요

2023-11-18 16:52 UTC, easyhooon commented
> 7. 일반적으로 Kotlin 함수의 매개변수는 default value가 없는 것들이 먼저 오고, 그 뒤에 default value가 있는 매개변수가 와야 합니다(Trailing lambda는 예외). Composable도 마찬가지로 default value가 없는 것, Modifier, default value가 있는 것 순서대로 와야 합니다. 이 PR을 포함하여 디자인 적용 PR에서 위 원칙대로 매개변수 순서를 바꿔 주시면 감사하겠습니다.

https://github.com/androidx/androidx/blob/androidx-main/compose/docs/compose-component-api-guidelines.md#modifier-parameter
그릏네요 first optional 이라길래 first 만 봤는데 optional 이 그 의미였군여

2023-11-18 23:34 UTC, easyhooon commented
1, 2, 3, 4, 5번을 [디자인 피드백 반영](https://github.com/mwy3055/MyVoca/pull/148/commits/5582f2ed5a01661e85745d557929f6123cc71067) 에서 수정했습니다.

2023-11-18 23:35 UTC, easyhooon commented
6, 7번을 [Modifier 관련 피드백 반영](https://github.com/mwy3055/MyVoca/pull/148/commits/8a045623412583db684e3ebbb97ffb381dc0f5f7) 에서 수정했습니다

2023-11-19 07:39 UTC, mwy3055 reviewed
## 변경 요청사항 확인

* 1번: 아이콘이 여전히 약간 어긋난 것 같아서, https://github.com/mwy3055/MyVoca/pull/148/commits/407755ed6e58aacb027f75d2a0435c10165a3fa3 에서 맞췄습니다. 지훈님 기기에서도 가운데 정렬된 걸로 보이면 바로 approve하겠습니다.
* 2, 3, 4, 5, 6, 7번: 확인했습니다.

## 제가 변경한 사항

새로 request change를 날리기엔 너무 작은 것들이라 그냥 제가 수정했습니다.

* https://github.com/mwy3055/MyVoca/pull/148/commits/8ea264367867257bf12806e8e430dea8e8da31d3: 일부 `modifier` 매개변수가 없는 composable에 `modifier` 매개변수를 추가했습니다.
* https://github.com/mwy3055/MyVoca/pull/148/commits/02a3ec236d47c92037e08a456445b86e5089d3ad: TextField가 에러 상태일 때 trailingIcon에 터치 이펙트가 뜨지 않도록 수정했습니다. 

## 코멘트

* **UI를 만들 때는 Figma에서 선언한 component 단위로 개발하시면 좋습니다**. 예를 들어 `AddWordScreen.kt` 파일의 `Word`는 `Row`와 `Column`이 매우 복잡하게 얽혀 있는데, Figma component 단위로 끊으면 가독성이 더 좋아지지 않을까요?
* 또, 유지보수 측면에서 수정사항을 한 번에 적용하기도 쉬워집니다. 예를 들어 https://github.com/mwy3055/MyVoca/pull/148/commits/02a3ec236d47c92037e08a456445b86e5089d3ad 커밋에서는 같은 변경사항을 단어와 뜻 composable에 두 번 적용했는데, `MyVocaTextInput`(가칭) composable이 있었다면 수정하기 더 쉬웠을 것 같습니다.
* 사실 `MyVocaTextInput`은 Figma에도 아직 분리돼있지 않습니다. 나중에 리팩토링 연습 겸 작업해보시면 좋을 것 같습니다. (필수는 아니지만 연습삼아)

2023-11-19 08:01 UTC, easyhooon commented
> 또, 유지보수 측면에서 수정사항을 한 번에 적용하기도 쉬워집니다. 예를 들어 https://github.com/mwy3055/MyVoca/commit/02a3ec236d47c92037e08a456445b86e5089d3ad 커밋에서는 같은 변경사항을 단어와 뜻 composable에 두 번 적용했는데, Figma에 디자인된 대로 WordInput composable이 있었다면 수정하기 더 쉬웠을 것 같습니다.

그러네요 사실 모든 컴포저블을 파일별로 분리해서 관리하고 싶었긴했는데(스크롤을 너무 많이해야해서) 너무 많이 바꾸는거 같아 하진 않았습니다.

혹시 모든 것이 마무리 된게 맞을까요? 맞다면 merge 하려고 합니다

2023-11-19 08:03 UTC, mwy3055 commented
> 지훈님 기기에서도 가운데 정렬된 걸로 보이면 바로 approve하겠습니다.

아이콘 가운데 정렬됐는지만 확인해 주세요

2023-11-19 08:03 UTC, mwy3055 commented
지금 ci가 좀 이상한데요 (starting 단계에서 30분 동안 멈춰 있음)

아이콘 정렬된 것만 확인하면 바로 approve 드릴게요

![image](https://github.com/mwy3055/MyVoca/assets/45386920/095f11cd-e95b-47e7-abba-e4827c80b45c)

2023-11-19 08:16 UTC, easyhooon commented
![image](https://github.com/mwy3055/MyVoca/assets/51016231/7147d38d-168d-437f-8ba4-ce294395da76)
에뮬레이터에서는(Pixel 5) 중앙으로 배치된걸로 보였는데 실기기(Galaxy zflip4)에서는 중앙보다 살짝 위에 있는걸로 보이긴합니다

2023-11-19 08:21 UTC, mwy3055 approved these changes
아이콘은 나중에 composable 전부 분리할 때 수정하시죠

이슈로 만들어 주세요

2023-11-19 08:27 UTC, easyhooon commented
> 이슈로 만들어 주세요

#151

2023-11-19 08:28 UTC, merged