퀴즈 화면 피그마 디자인에 맞게 변경
mwy3055/MyVoca pull request #152
Opened 2023-11-19 09:31 UTC by easyhooon

- 퀴즈 화면 피그마 디자인에 맞게 변경 
- 퀴즈 선택지가 중복으로 출력되는 경우가 존재하여, 이를 수정

2023-11-19 09:32 UTC, easyhooon commented
맞았습니다!!, 틀렸습니다 다이얼로그 내에서 전체 뜻을 보여주는 것에 대해선 정책이 정해지면 수정하겠습니다

2023-11-21 11:01 UTC, mwy3055 requested changes
1. 화면 맨 하단 `VersusView`의 삼각형이 약간 어긋나 있습니다. 수정 가능할까요?
![image](https://github.com/mwy3055/MyVoca/assets/45386920/9deb2ea3-61d7-47e9-8686-44dda3e8de45)

2. 정답/오답 팝업이 떴을 때 뒷 화면이 검게 처리되어야 합니다. 기술적으로 불가능한가요? Compose `Dialog`를 전체 화면에 띄우면 될 것 같은데 한번 확인해 주세요
![image](https://github.com/mwy3055/MyVoca/assets/45386920/bdefbc99-1f06-4a23-ab59-28162a49f23d)

3. 앱바에 적용된 shadow도 스타일로 정의한 후 적용해야 하는데, 이건 별로 중요하지는 않으니 일단 넘어갈게요

4. `WordMeaning`에서 단어 품사와 뜻 텍스트에 `MaterialTheme.typography.bodyLarge`가 적용되어야 합니다. 사실 퀴즈 단어도 디자인에서 사용한 텍스트 스타일이 적용되지 않았습니다. 수정 부탁드려요. (찾아보니 `QuizOption`에서 CompositionLocal로 값을 주고 있네요)

2023-11-21 12:03 UTC, easyhooon commented
> 정답/오답 팝업이 떴을 때 뒷 화면이 검게 처리되어야 합니다. 기술적으로 불가능한가요? Compose Dialog를 전체 화면에 띄우면 될 것 같은데 한번 확인해 주세요

이거 에뮬레이터에서 뒤에 딤 처리가 안되는 이슈가 있더군요 저도 그래서 찾아봤는데 실기기에서는 정상적으로 딤처리가 됩니다

2023-11-21 12:28 UTC, easyhooon commented
> 화면 맨 하단 VersusView의 삼각형이 약간 어긋나 있습니다. 수정 가능할까요?
허걱 핸드폰 마다 다르게 보이는건가.. 확인해보겠습니다!

2023-11-21 12:58 UTC, easyhooon commented
> WordMeaning에서 단어 품사와 뜻 텍스트에 MaterialTheme.typography.bodyLarge가 적용되어야 합니다. 사실 퀴즈 단어도 디자인에서 사용한 텍스트 스타일이 적용되지 않았습니다. 수정 부탁드려요. (찾아보니 QuizOption에서 CompositionLocal로 값을 주고 있네요)

https://developer.android.com/jetpack/compose/designsystems/material3?hl=ko
아 공식문서에 각각 크기가 얼만지 명시되어있었군여 이거 보고 고쳐보겠슴니다

2023-11-21 13:14 UTC, mwy3055 commented
> https://developer.android.com/jetpack/compose/designsystems/material3?hl=ko 아 공식문서에 각각 크기가 얼만지 명시되어있었군여 이거 보고 고쳐보겠슴니다

공식 문서가 아니라 Figma에 선언되어 있습니다. 피그마의 `Material 3 Design Kit for MyVoca` 파일에서 확인하실 수 있습니다.

![image](https://github.com/mwy3055/MyVoca/assets/45386920/6eab8df1-3c58-4c1f-b91a-f503706f77f9)

2023-11-21 14:39 UTC, easyhooon commented
> 화면 맨 하단 VersusView의 삼각형이 약간 어긋나 있습니다. 수정 가능할까요?

혹시 이거 실기기에서 확인 해보실수있으실까요? 도저히 원인을 모르겠군요 ;ㅁ;

2023-11-22 01:22 UTC, easyhooon commented
4번을 [QuizScreen 내에 하드 코딩 된 textSize MaterialTheme.typography textStyle 로 변경](https://github.com/mwy3055/MyVoca/pull/152/commits/26f642d976fee321ed2380f2e5e2598558a73354) 에서 수정했습니다

2023-11-22 02:30 UTC, easyhooon commented
> 4번을 [QuizScreen 내에 하드 코딩 된 textSize MaterialTheme.typography textStyle 로 변경](https://github.com/mwy3055/MyVoca/pull/152/commits/26f642d976fee321ed2380f2e5e2598558a73354) 에서 수정했습니다

해당 커밋에서 VersusElement 내부의 텍스트도 MaterialTheme.typography 의 것으로 대체하였더니 Canvas 의 삐져 나온 것이 사라졌습니다(?) 쨌든 1번도 수정했습니다

2023-11-22 10:43 UTC, mwy3055 approved these changes
폰트 크기와 관련있었나 보네요? 확인했습니다

2023-11-22 10:43 UTC, mwy3055 commented on app/src/main/java/hsk/practice/myvoca/ui/components/WordContent.kt
> +    val textStyle = LocalTextStyle.current
사실 이렇게 명시적으로 주지 않아도 됩니다. `MyVocaText`에서 `LocalTextStyle.current`를 기본값으로 받고 있기 때문입니다.

하지만 수정하실 필요는 없습니다. 그냥 그렇다고요

2023-11-22 10:48 UTC, easyhooon commented on app/src/main/java/hsk/practice/myvoca/ui/components/WordContent.kt
> +    val textStyle = LocalTextStyle.current
오오.. 그렇군여 맞네요 제가 만들어놓고 잊어먹었네여

2023-11-22 10:48 UTC, merged