디테일한 부분 채우기
mwy3055/MyVoca pull request #156
Opened 2023-12-01 17:58 UTC by easyhooon

- LoadingIndicator 배경 색상 변경
- Deprecated 된 함수, 권장 하는 함수로 교체
- 모든 파일에 trailing commna 적용
- 누락된 icon 컬러 지정(다크 모드 대응)

2023-12-02 12:30 UTC, mwy3055 requested changes
얼추 된 것 같습니다. 하나만 수정 부탁드릴게요.

`WordContent`의 단어와 뜻 사이가 너무 넓어졌습니다. 넓힌 부분의 반만 다시 좁힐 수 있을까요? (예를 들어 16dp 늘렸다면 8dp로 수정)

![image](https://github.com/mwy3055/MyVoca/assets/45386920/5ab8f99b-6994-436b-
b19d-90574f910504)

2023-12-02 12:30 UTC, mwy3055 commented on app/src/main/java/hsk/practice/myvoca/data/VocabularyImpl.kt
> +        fun findByKorean(korean: String) = entries.find { it.korean == korean }
`values()`가 deprecated됐나요?

2023-12-02 12:30 UTC, mwy3055 commented on app/src/main/java/hsk/practice/myvoca/work/CreateTodayWordWork.kt
> +        ExistingPeriodicWorkPolicy.UPDATE,
이건 잘 바뀐 것 같아요. `REPLACE`는 기존 work를 그냥 죽여버렸는데 `UPDATE`는 조금 더 신사적으로 교체하는 옵션이더라고요

2023-12-02 12:55 UTC, mwy3055 commented
저도 커밋 몇개만 올렸는데, 이 PR과 크게 상관없는 수정사항만 올렸습니다. 리뷰할 것도 없지만 그냥 참고하시라고 적어 봅니다.

- https://github.com/mwy3055/MyVoca/pull/156/commits/245aaa7aa58cd2327156f7178839be559438b166: 제 데스크탑에서 빌드한 앱이 Firebase Google 로그인이 불가능하던 문제를 수정했습니다. 데스크탑의 SHA-1 해시를 Firebase에 등록한 후 `google-services.json`을 교체하면 되는 문제였습니다.
- https://github.com/mwy3055/MyVoca/pull/156/commits/4217418803a4d451d75666527bb0950489475f77: Firebase 로그인 실패시 stack trace도 출력하도록 수정했습니다.
- https://github.com/mwy3055/MyVoca/pull/156/commits/77bb027c8db79942e16c8bdb0836053bdeccb73e: 스크린샷 촬영을 위해 프로필 화면을 약간 수정했습니다. 로그인 후 프로필 사진과 username이 너무 크게 보이는 문제가 있어 크기만 조금 줄였습니다.

2023-12-03 00:46 UTC, easyhooon commented on app/src/main/java/hsk/practice/myvoca/data/VocabularyImpl.kt
> +        fun findByKorean(korean: String) = entries.find { it.korean == korean }
아 정확힌 deprecated 된 것은 아니고 IDE 측에서 entries 로 바꾸라고 권장을 해주어서 변경해줬습니다. pr 상세 내용 수정해놨습니다

2023-12-03 00:48 UTC, easyhooon commented
> WordContent의 단어와 뜻 사이가 너무 넓어졌습니다. 넓힌 부분의 반만 다시 좁힐 수 있을까요? (예를 들어 16dp 늘렸다면 8dp로 수정)

[WordTitle, WordMeanings 사이의 간격 조정](https://github.com/mwy3055/MyVoca/pull/156/commits/df66a263eb8b66d85c3fc896c47c8c93ba917948) 에서 수정하였습니다

2023-12-03 01:10 UTC, mwy3055 commented on app/src/main/java/hsk/practice/myvoca/data/VocabularyImpl.kt
> +        fun findByKorean(korean: String) = entries.find { it.korean == korean }
1.9.0에 추가됐네요. 이런 이유가 있다고 하네요.

https://engineering.teknasyon.com/kotlin-enums-replace-values-with-entries-bbc91caffb2a

2023-12-03 01:11 UTC, mwy3055 approved these changes
ok

수고하셨습니다. 작업 완료.

2023-12-03 01:22 UTC, merged